### ISSUE TITLE
White vertical line after start date while using `DatePickerModal` for range

### ISSUE THREAD

**Issue by fabriziocucci** [web-ridge/react-native-paper-dates#281] opened 2023-04-16 17:04 UTC
### Current behaviour
There seems to be a visual defect when using the `DatePickerModal` for range selection, specifically, a white vertical line appears next to the start date interrupting the range selection (see image below).

### Expected behaviour
I would not expect the white vertical line to show up.

### How to reproduce?
I'm simply using the component as shown below:
```
<DatePickerModal
      disableStatusBarPadding={true}
      endDate={endDateMemo}
      locale="en"
      mode="range"
      onConfirm={onConfirm}
      onDismiss={onDismiss}
      startDate={startDateMemo}
      uppercase={false}
      visible={visible}
/>
```

### Preview
![white-line](https://user-images.githubusercontent.com/8156463/232328522-d65d7658-9936-4878-b3a7-830f7bebb4c4.jpeg)

### Your Environment

| software                               | version
| -------------------------- | -------
| react-native-paper             | 5.6.0
| react-native-paper-dates  | 0.15.1

**Comment by iM-GeeKy** [comment] 2023-04-16 17:08
Hi @fabriziocucci, this looks to be a duplicate of https://github.com/web-ridge/react-native-paper-dates/issues/271 and should be addressed in this [PR](https://github.com/web-ridge/react-native-paper-dates/pull/272) when @RichardLindhout is available to review it. Feel free to take a look, you should be able to apply a local patch until its merged and published.

**Comment by fabriziocucci** [comment] 2023-04-16 17:16
Thanks for the prompt reply @iM-GeeKy, I'll subscribe to the PR and close this! 👍

**Closed** 2023-04-16 17:16 UTC
Labels: bug
