### ISSUE TITLE
How prevent DatePickerInput default of current date?

### ISSUE THREAD

**Issue by julianpensionjar** [web-ridge/react-native-paper-dates#162] opened 2022-05-24 08:55 UTC
I'm trying to use DatePickerInput following the example here: https://github.com/web-ridge/react-native-paper-dates/blob/master/example/src/ReadMeExampleDatePickerInput.tsx

```
import * as React from 'react'

import { DatePickerInput } from '../../src/index'

export default function ReadMeExampleDatePickerInput() {
  const [inputDate, setInputDate] = React.useState<Date | undefined>(undefined)

  return (
    <>
      <DatePickerInput
        locale="en"
        label="Birthdate"
        value={inputDate}
        onChange={(d) => setInputDate(d)}
        inputMode="start"
        autoComplete="birthdate-full"
        // mode="outlined" (see react-native-paper docs)
        // other react native TextInput props
      />
    </>
  )
}
```

In my case, the input is wrapped with react-hook-form (https://react-hook-form.com/) for control/validation.

When inputDate is undefined, the input field shows the **current** date, which seems a bit odd? This isn't the real underlying value managed by react-hook-form, hence attempting to submit the form results in a validation error (expected, because the user has not actually entered/selected a date yet!)

Am I missing something? Is there a way to have the input field blank, or better still use the placeholder value supported by the underlying TextInput from react-native-paper? Currently, it is confusing to show the user a date on-screen that "isn't actually there".

**Comment by RichardLindhout** [comment] 2022-08-25 18:54
Can you check if this is resolved in the next version which will be released later this evening?

**Comment by Bartosz-L** [comment] 2022-12-02 15:37
The problem is still there.

**Comment by iM-GeeKy** [comment] 2023-01-10 23:55
This should now be fixed. It was resolved in this commit in the following PR. https://github.com/web-ridge/react-native-paper-dates/pull/229/commits/d4025bd065aa83a3468fca0369f1babefa5b2c2f

**Closed by iM-GeeKy** 2023-01-10 23:55 UTC
Labels: bug
