### ISSUE TITLE
Make it possible to start the week on monday

### ISSUE THREAD

**Issue by rathierry** [web-ridge/react-native-paper-dates#116] opened 2021-11-08 14:16 UTC
How to do it with version 0.4.6 ?

**Comment by rathierry** [comment] 2021-11-09 06:56
@RichardLindhout, is this already possible with version 0.4.6 ?!!!
Thanks

**Comment by RichardLindhout** [comment] 2021-11-09 21:14
Nope, still not possible, I think it's hard + I don't have time to implement it a.t.m.

**Comment by RichardLindhout** [comment] 2021-11-09 21:14
I would accept PR's which implement this feature ofcourse!

**Comment by RichardLindhout** [comment] 2021-11-09 21:15
@rathierry duplicate of https://github.com/web-ridge/react-native-paper-dates/issues/20

**Comment by RichardLindhout** [comment] 2021-11-09 21:16
Locked please continue discussion in: https://github.com/web-ridge/react-native-paper-dates/issues/20

**Closed by RichardLindhout** 2021-11-09 21:15 UTC
Labels: enhancement
