### ISSUE TITLE
Date Range has a Small Gap in Between Certain Dates

### ISSUE THREAD

**Issue by michael-agilesrc** [web-ridge/react-native-paper-dates#271] opened 2023-03-21 19:43 UTC
### Current behavior
Between Certain dates in the Date range, there is a gap in the range highlight.

### How to reproduce?
On the [date range documentation's snack](https://snack.expo.dev/@fitzwabs/react-native-paper-dates-range-picker?platform=ios) you can launch it on the IOS simulator and see this. If you select a range ending on Friday (ex: March 15, 2023 - March 17, 2023), there will be a small gap by the end date. This is much more noticeable with a dark theme but still can be seen with a light theme.

Note: The date it appears on changes per device. On my personal project and device, it'll appear with a date range ending on Thursday or Saturday, but I have a coworker for whom it'll appear with a date range ending on Thursday, Friday, or Saturday

### Preview
In the image below, there's a small gap between March 16, 2023 and March 17, 2023
![Screen Shot 2023-03-21 at 3 38 15 PM](https://user-images.githubusercontent.com/107625462/226722146-a2f16c9e-62bd-425a-a255-bffd84660068.png)

**Comment by iM-GeeKy** [comment] 2023-03-21 19:52
Sounds like a duplicate of this https://github.com/web-ridge/react-native-paper-dates/issues/149

**Comment by michael-agilesrc** [comment] 2023-03-21 19:56
Hey, @iM-GeeKy It isn't a duplicate of that. I solved the issue mentioned in #149 on my end by setting the start date's hours, minutes, seconds, and milliseconds to 0.

**Comment by michael-agilesrc** [comment] 2023-03-21 19:58
> Hey! Thanks for opening the issue. Can you provide a minimal repro which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.dev](https://snack.expo.dev). If it's not possible to repro it on [snack.expo.dev](https://snack.expo.dev), then you can also provide the repro in a GitHub repository.

I mentioned this in the description above, but the snack from the date range documentation works perfectly fine to show this. 

Link: https://snack.expo.dev/@fitzwabs/react-native-paper-dates-range-picker?platform=ios
Platform: IOS but the same thing happens on android when I locally test

**Comment by iM-GeeKy** [comment] 2023-04-22 11:17
Closed by https://github.com/web-ridge/react-native-paper-dates/issues/281

**Closed by iM-GeeKy** 2023-04-22 11:17 UTC
Labels: bug, good first issue, needs repro, repro provided

**Comment by michael-agilesrc** [comment] 2023-04-26 13:53
Hey, @iM-GeeKy thanks for making the changes! Everything looks good on IOS, but Android still seems to have this problem on version 0.16.1.
