### ISSUE TITLE
[Issue] TimeInput unreadable when input is selected and primary color is black

### ISSUE THREAD

**Issue by fabriziocucci** [web-ridge/react-native-paper-dates#192] opened 2022-08-27 15:15 UTC
An image speaks more than a thousand of words:

<img width="366" alt="Screenshot 2022-08-27 at 17 13 02" src="https://user-images.githubusercontent.com/8156463/187036234-aeb9bd29-a5dd-40c7-8c0c-8906188f6f2c.png">

As you can see, the hour `TimeInput` is selected and pm is selected in the `AmPmSwitcher`.

Any workaround available until a proper fix is baked?

**Comment by fdelacruzsoto** [comment] 2022-09-08 01:59
I'm looking for a workaround like this, in my case the issue is on the buttons, when in dark mode, my primary color is also a dark color, which is difficult to read, it would be great if there is a way to set these colors.

**Comment by stuart-clark-45** [comment] 2022-11-11 16:22
I found a work around. Wrap your modals in an another provider and adjust the primary color 

```
import { Provider as PaperProvider } from 'react-native-paper';

const datetimePickerTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    primary: '#8eb7ff',
  },
};

 <PaperProvider theme={datetimePickerTheme}>
        <DatePickerModal
          locale="en"
          mode="single"
          visible={showDateModal}
          onDismiss={onDismissDateModal}
          date={value}
          onConfirm={noOp}
          onChange={(e: Parameters<SingleChange>[0]) =>
            updateValue(e.date as Date)
          }
          saveLabelDisabled={true}
          saveLabel=" "
          label={label}
          closeIcon="arrow-left"
        />
        <TimePickerModal
          visible={showTimeModal}
          onDismiss={onDismissTimeModal}
          onConfirm={onConfirmTime}
          hours={value?.getHours()}
          minutes={value?.getMinutes()}
        />
      </PaperProvider>
```

**Comment by RichardLindhout** [comment] 2022-12-27 20:26
PR is welcome!

**Comment by RichardLindhout** [comment] 2023-12-21 19:44
I can't reproduce this.

**Comment by RichardLindhout** [comment] 2023-12-21 19:45
```
  m3Theme.colors.primary = '#000000'
  m2Theme.colors.primary = '#000000'
  ```

**Comment by RichardLindhout** [comment] 2023-12-21 19:52
This is fixed now in m2 where primary is black. If you have this in m3 please fix your theme:

You need to have onPrimaryContainer white!
```
  m3Theme.colors.primaryContainer = '#000000'
  m3Theme.colors.onPrimaryContainer = '#000000'
  ```

**Closed by RichardLindhout** 2023-12-21 19:52 UTC
Labels: bug, enhancement, help wanted, Priority
